### ISSUE TITLE
Which files should be downloaded from the DFC2019 official website?

### ISSUE THREAD

**Issue by zhaob10** [CVEO/S3Net#2]
@1128yqy  thank you for your great work. I want to know that which files should be downloaded from the  DFC2019 official website. Do you download "Track 2/Training data/RGB images", "Track2/Training data/reference" and "Track2/Validation Data" as training/test/validation dataset ？Thank you in advance.

**Comment by 1128yqy** [comment]
The official validation data folder does not contain ground truth, so only the training data is needed. The specific dataset division used in this paper can be referenced at https://github.com/CVEO/S3Net/issues/1#issuecomment-1978312611.
